"""Pre-build: inject the env's flash size into sdkconfig.defaults.<env>.

PlatformIO does not propagate `board_upload.flash_size` into the IDF
sdkconfig, so the binary is built with whatever `CONFIG_ESPTOOLPY_FLASHSIZE`
the global sdkconfig.defaults specifies. This script writes a per-env
sdkconfig override that PlatformIO's espidf builder will pick up via the
SDKCONFIG_DEFAULTS env var.
"""
import os

Import("env")  # type: ignore

PROJECT_DIR = env["PROJECT_DIR"]
ENV_NAME = env["PIOENV"]

board = env.BoardConfig()
flash_size = board.get("upload.flash_size", "4MB")  # e.g. "4MB", "8MB", "16MB"

# Map to the matching Kconfig symbol
size_to_symbol = {
    "2MB":  "CONFIG_ESPTOOLPY_FLASHSIZE_2MB",
    "4MB":  "CONFIG_ESPTOOLPY_FLASHSIZE_4MB",
    "8MB":  "CONFIG_ESPTOOLPY_FLASHSIZE_8MB",
    "16MB": "CONFIG_ESPTOOLPY_FLASHSIZE_16MB",
    "32MB": "CONFIG_ESPTOOLPY_FLASHSIZE_32MB",
}
all_symbols = list(size_to_symbol.values())
chosen = size_to_symbol.get(flash_size)
if not chosen:
    print("fix_flash_size: unknown flash size %r — leaving sdkconfig alone" % flash_size)
else:
    override_path = os.path.join(PROJECT_DIR, "sdkconfig.defaults.%s" % ENV_NAME)
    lines = ["# AUTO-GENERATED by scripts/fix_flash_size.py - do not edit\n"]
    for sym in all_symbols:
        if sym == chosen:
            lines.append("%s=y\n" % sym)
        else:
            lines.append("# %s is not set\n" % sym)
    lines.append('CONFIG_ESPTOOLPY_FLASHSIZE="%s"\n' % flash_size)

    new_content = "".join(lines)
    needs_write = True
    if os.path.isfile(override_path):
        with open(override_path) as f:
            if f.read() == new_content:
                needs_write = False
    if needs_write:
        with open(override_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("fix_flash_size: wrote %s (%s)" % (os.path.basename(override_path), flash_size))

    # Tell the IDF builder to merge this file with sdkconfig.defaults.
    # PlatformIO's espidf.py reads SDKCONFIG_DEFAULTS via the cmake project_include path.
    existing = os.environ.get("SDKCONFIG_DEFAULTS", "")
    if override_path not in existing:
        os.environ["SDKCONFIG_DEFAULTS"] = (
            "sdkconfig.defaults;%s" % override_path
            if not existing
            else "%s;%s" % (existing, override_path)
        )
