"""PlatformIO pre-build script: gzip data/ files and embed into web_assets.h."""
import os
import gzip

Import("env")  # type: ignore

PROJECT_DIR = env["PROJECT_DIR"]
DATA_DIR = os.path.join(PROJECT_DIR, "data")
OUT_FILE = os.path.join(PROJECT_DIR, "src", "web_assets.h")
SCRIPT_FILE = os.path.join(PROJECT_DIR, "scripts", "gen_web_assets.py")

FILES = [
    ("index_html",    "index.html"),
    ("style_css",     "style.css"),
    ("app_js",        "app.js"),
    ("setup_html",    "setup.html"),
    ("settings_html", "settings.html"),
]


def c_bytes(data: bytes) -> str:
    """Convert bytes to a C array body using hex escapes."""
    out = []
    line_len = 0
    for b in data:
        out.append("\\x%02x" % b)
        line_len += 4
        if line_len >= 76:
            out.append('"\n    "')
            line_len = 0
    return "".join(out)


def generate():
    needs_regen = not os.path.isfile(OUT_FILE)
    if not needs_regen:
        out_mtime = os.path.getmtime(OUT_FILE)
        for _, fname in FILES:
            fpath = os.path.join(DATA_DIR, fname)
            if os.path.getmtime(fpath) > out_mtime:
                needs_regen = True
                break
        if os.path.isfile(SCRIPT_FILE) and os.path.getmtime(SCRIPT_FILE) > out_mtime:
            needs_regen = True

    if not needs_regen:
        return

    lines = [
        "/* AUTO-GENERATED — do not edit. Generated by scripts/gen_web_assets.py */",
        "#pragma once",
        "#include <stddef.h>",
        "",
    ]

    total_raw = 0
    total_gz = 0

    for sym, fname in FILES:
        fpath = os.path.join(DATA_DIR, fname)
        with open(fpath, "rb") as f:
            raw = f.read()
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        total_raw += len(raw)
        total_gz += len(gz)

        lines.append("/* %s: %d -> %d bytes */" % (fname, len(raw), len(gz)))
        lines.append("static const char %s[] =" % sym)
        lines.append('    "%s";' % c_bytes(gz))
        lines.append("static const size_t %s_len = %d;" % (sym, len(gz)))
        lines.append("")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Generated %s (%d -> %d bytes, %.0f%% saving)" %
          (OUT_FILE, total_raw, total_gz, 100 * (1 - total_gz / total_raw)))


generate()
